### ISSUE TITLE
Using lodash-webpack-plugin breaks redux-persist functionality

### ISSUE THREAD

**Issue by creage** [lodash/lodash-webpack-plugin#54]
I'm not sure if it is lodash's issue (probably not), but adding
`new LodashModuleReplacementPlugin`
to webpack plugins, causes redux-persist stopping write it's data to localStorage.

**Comment by jdalton** [comment]
Hi @creage!

This plugin rewrites the module paths of `lodash` to remove feature sets and reduce extraneous functionality to create smaller bundles.

**Comment by rt2zz** [comment]
This ended up being a strange issue that I never fully figured out:

lodash-webpack-plugin was somehow converting the forEach important to only handle forEach on arrays. Since we relied on collection iteration this broke things. I have since replaced that usage of forEach with an `object.keys -> foreach` call, but I am curious if anyone else comes across weird behavior like this.

**Comment by jdalton** [comment]
Enable the collections feature set.

**Comment by rt2zz** [comment]
ah, @jdalton as a library author what would be the best way to "enforce" this? i.e. I cannot reasonably expect every consumer to know to set `collections: true`.

**Comment by jdalton** [comment]
Your consumers should be consuming the bundled build.
