### ISSUE TITLE
Dependency to Babel

### ISSUE THREAD

**Issue by code-chris** [lodash/lodash-webpack-plugin#98]
Hi,
I've two questions about this plugin:
- I saw, that this has a dependency to some babel packages. But in the code, there is no babel used. Is there a reason?
- The example shows the LodashModuleReplacementPlugin and the babel-loader configuration where lodash is defined as plugin. Is this the only way to use the lodash-webpack-plugin? I tried this in a small test without babel but with typescript. So the LodashModuleReplacementPlugin in the plugins array is the only reference. But this seems not to work.... The artifacts are still about 540KB.

Thanks!

**Comment by jdalton** [comment]
Hi @code-chris!

The babel dependencies for the project are dev dependencies. The plugin works well combined with [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) because it streamlines cherry-picking modules turning
```js
_.chunk([1, 2, 3, 4], 2)
```
into
```
var _chunk = require('lodash/chunk')
_chunk([1, 2, 3, 4], 2)
```
This plugin works with the cherry-picked modules to reduce their bundle size.

**Comment by code-chris** [comment]
@jdalton So this plugin has no effect in standalone usage without babel-plugin-lodash?

**Comment by jdalton** [comment]
> So this plugin has no effect in standalone usage without babel-plugin-lodash

The `babel-plugin-lodash` plugin makes cherry-picking easier. Cherry-picking is the key.
You have to specify the modules to use `require('lodash/chunk')` so that this webpack plugin can rewire the requested internal modules. If you just use the monolithic build there is no modules as it's a single complete file.

**Comment by code-chris** [comment]
Ok, I understand.... Thanks for your quick reply!

**Comment by code-chris** [comment]
Hi @jdalton,
I've written a new [loader](https://github.com/code-chris/lodash-loader) for webpack now to optimize bundle sizes. It has no dependencies to other loaders or plugins and can be used both in babel or typescript based projects.

If you see some bugs or you have ideas to improve, please let me know ;).
